INSERT INTO CATEGORY (id, name)
SELECT 1, 'Goods'
WHERE NOT EXISTS(SELECT * FROM CATEGORY WHERE id = 1);

INSERT INTO CATEGORY (id, name)
SELECT 2, 'Photo Card'
WHERE NOT EXISTS(SELECT * FROM CATEGORY WHERE id = 2);

INSERT INTO CATEGORY (id, name)
SELECT 3, 'album'
WHERE NOT EXISTS(SELECT * FROM CATEGORY WHERE id = 3);
